version: '2'

services:
        web:
                build: .
                ports:
                        - '8037:80'
                stdin_open: true
                tty: true
                volumes:
                        - ./source:/var/www/html
                        - ./logs:/var/log/apache2
                        - ./flag:/flag
